#!/usr/bin/env python

import os

hooks_dir = os.path.dirname(os.path.abspath(__file__))
relative_dir = os.path.join(hooks_dir, '../..')
project_root = os.path.abspath(relative_dir)
def switch_contents(path, fi):
  git_included_fi = os.path.join(project_root, path, fi)
  confidential_fi = os.path.join(project_root, path, '_%s' % fi)

  with open(git_included_fi, 'rU') as fh:
    git_included_contents = fh.read()

  with open(confidential_fi, 'rU') as fh:
    confidential_contents = fh.read()

  with open(git_included_fi, 'w') as fh:
    fh.write(confidential_contents)

  with open(confidential_fi, 'w') as fh:
    fh.write(git_included_contents)


protected_files = [
    ('', 'hgrc'),
    ('', 'netrc'),
    ('ssh', 'bossylobster_rsa'),
    ('ssh', 'bossylobster_rsa.pub'),
    ('ssh', 'github_rsa'),
    ('ssh', 'github_rsa.pub'),
    ('ssh', 'highorder_rsa'),
    ('ssh', 'highorder_rsa.pub'),
]
for path, fi in protected_files:
  switch_contents(path, fi)
